# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'NewsMobileApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsMobileApp
  pod 'GoogleMaps', '6.1.0'
  pod 'Google-Maps-iOS-Utils', '3.4.0'

  target 'NewsMobileAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsMobileAppUITests' do
    # Pods for testing
  end

end
